apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-worker
automountServiceAccountToken: false
