apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portal-development
resources:
  - ../../base
  - namespace.yaml
configMapGenerator:
  - name: portal-runtime-config
    literals:
      - APP_ENV=development
      - APP_ORIGIN=http://portal.localhost
      - NEXT_PUBLIC_APP_ENV=development
      - NEXT_PUBLIC_RELEASE_REVISION=local-development
      - PORT=3001
      - RELEASE_REVISION=local-development
generatorOptions:
  disableNameSuffixHash: true
commonAnnotations:
  portal.remeselnicky.dev/release-revision: local-development
images:
  - name: registry.invalid/remeselnicky-portal/web
    newTag: local-development
  - name: registry.invalid/remeselnicky-portal/api
    newTag: local-development
  - name: registry.invalid/remeselnicky-portal/worker
    newTag: local-development
