import { randomUUID } from "node:crypto";

import postgres, { type Sql } from "postgres";

export type IsolatedDatabaseEnvironment = "development" | "staging" | "test";

export interface IsolatedPostgresContext {
  readonly databaseName: string;
  readonly environment: IsolatedDatabaseEnvironment;
  readonly sql: Sql;
}

export async function withIsolatedPostgresDatabase<Result>(input: {
  readonly baseConnectionString: string;
  readonly environment: IsolatedDatabaseEnvironment;
  readonly run: (context: IsolatedPostgresContext) => Promise<Result>;
}): Promise<Result> {
  const baseUrl = validateBaseUrl(
    input.baseConnectionString,
    input.environment,
  );
  const databaseName = `portal_it_${randomUUID().replaceAll("-", "")}`;
  assertGeneratedDatabaseName(databaseName);
  const admin = postgres(baseUrl.toString(), {
    max: 1,
    onnotice: () => undefined,
    prepare: false,
  });
  let created = false;
  let target: Sql | undefined;
  try {
    await admin`CREATE DATABASE ${admin(databaseName)} TEMPLATE template0`;
    created = true;
    await setGeneratedDatabaseEnvironment(
      admin,
      databaseName,
      input.environment,
    );
    const targetUrl = new URL(baseUrl);
    targetUrl.pathname = `/${databaseName}`;
    target = postgres(targetUrl.toString(), {
      max: 4,
      onnotice: () => undefined,
      prepare: true,
    });
    return await input.run(
      Object.freeze({
        databaseName,
        environment: input.environment,
        sql: target,
      }),
    );
  } finally {
    try {
      if (target !== undefined) await target.end({ timeout: 5 });
      if (created) {
        assertGeneratedDatabaseName(databaseName);
        await admin`DROP DATABASE ${admin(databaseName)} WITH (FORCE)`;
      }
    } finally {
      await admin.end({ timeout: 5 });
    }
  }
}

async function setGeneratedDatabaseEnvironment(
  admin: Sql,
  databaseName: string,
  environment: IsolatedDatabaseEnvironment,
): Promise<void> {
  assertGeneratedDatabaseName(databaseName);
  switch (environment) {
    case "development":
      await admin`ALTER DATABASE ${admin(databaseName)} SET portal.environment TO 'development'`;
      return;
    case "staging":
      await admin`ALTER DATABASE ${admin(databaseName)} SET portal.environment TO 'staging'`;
      return;
    case "test":
      await admin`ALTER DATABASE ${admin(databaseName)} SET portal.environment TO 'test'`;
  }
}

function validateBaseUrl(
  value: string,
  environment: IsolatedDatabaseEnvironment,
): URL {
  if (
    environment !== "development" &&
    environment !== "staging" &&
    environment !== "test"
  ) {
    throw new Error(
      "Isolated test databases are allowed only in development, staging or test.",
    );
  }
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new TypeError("Integration database connection string is malformed.");
  }
  if (url.protocol !== "postgres:" && url.protocol !== "postgresql:") {
    throw new TypeError("Integration database must use PostgreSQL.");
  }
  const database = decodeURIComponent(url.pathname.slice(1)).toLowerCase();
  const loopback = ["127.0.0.1", "::1", "localhost"].includes(
    url.hostname.toLowerCase(),
  );
  if (environment === "staging") {
    const sslMode = url.searchParams.get("sslmode");
    const remoteTls =
      sslMode === "require" ||
      sslMode === "verify-ca" ||
      sslMode === "verify-full";
    if (!database.includes("staging") || (!loopback && !remoteTls)) {
      throw new Error(
        "Staging isolation requires a staging-named database and TLS for remote hosts.",
      );
    }
  } else if (!loopback || !/(?:^|[_-])(test|dev)(?:$|[_-])/u.test(database)) {
    throw new Error(
      "Development/test isolation requires a loopback test/dev database.",
    );
  }
  return url;
}

function assertGeneratedDatabaseName(value: string): void {
  if (!/^portal_it_[0-9a-f]{32}$/u.test(value)) {
    throw new Error(
      "Refusing to mutate a database not generated by the harness.",
    );
  }
}
