apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.yaml
configMapGenerator:
  - name: portal-system-health-dashboard
    files:
      - system-health-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
